# Generated by Django 5.1.1 on 2024-09-21 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=255)),
                ("quantity", models.FloatField()),
                ("total_price", models.FloatField(blank=True)),
                ("price_per_unit", models.FloatField(blank=True)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("ST", "Stocking"), ("SO", "Sold")],
                        default="ST",
                        max_length=2,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="inventory.category",
                    ),
                ),
            ],
            options={
                "ordering": ("date", "transaction_type"),
            },
        ),
    ]
